# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: "23.1.0"
    hooks:
    -   id: black
        args: [--line-length=80, --exclude=setup.py]
-   repo: https://github.com/pycqa/flake8
    rev: "6.0.0"
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.0.1"
    hooks:
    -   id: mypy
        args: [--strict, --disallow-untyped-calls]
        exclude: "(tests|doc)/.*"
        additional_dependencies:
        -   types-setuptools
        -   rich
        -   subc
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
    -   id: reorder-python-imports
-   repo: https://github.com/netromdk/vermin
    rev: v1.5.2
    hooks:
    -   id: vermin
        args: ['-t=3.6-', '--violations', '--backport', 'dataclasses', '--eval-annotations']
